### PR TITLE
Fix #80: find correct python path for blender 2.92 and before

### LINKED ISSUE #80: AttributeError: 'bpy.app' object has no attribute 'binary_path_python'
`bpy.app.binary_path_python` was deprecated in 2.91 and removed for 2.92 in favor of `sys.executable` by the following commit:
https://developer.blender.org/rB6527a14cd2ceaaf529beae522ca594bb250b56c9
As a result, this extension stopped working because of the error on startup:
`AttributeError: 'bpy.app' object has no attribute 'binary_path_python'`

Strange, but for me sys.executable returns path to the Blender executable:
```
>>> import sys
>>> sys.executable
'/home/lissanro/pkgs/blender/blender-2.92.0-cac8a7cddb56-linux64/blender'
```
I found https://blender.stackexchange.com/questions/139718/install-pip-and-packages-from-within-blender-os-independently where it is suggested to use `sys.prefix` instead, and my solution below is based on this suggestion. I do not know if using `bpy.app.binary_path_python` is necessary for compatibility with old Blender versions. If it isn't, the following change in `environment.py` could solve the issue:
```
import sys
python_path = next((Path(sys.prefix)/"bin").glob("python*"))
```
If it is necessary to use `bpy.app.binary_path_python` for old Blender versions, then the following code would work:
```
try:
    python_path = Path(bpy.app.binary_path_python)
except AttributeError:
    import sys
    python_path = next((Path(sys.prefix)/"bin").glob("python*"))

```
Since I'm not sure what is the best fix for this, I decided to open an issue instead of PR.

### LINKED ISSUE #99: Version 0.0.15 could not install debugpy
Version 0.0.14 works perfectly OK.
After upgrading to 0.0.15 and issuing the Blender: Start command I now get

> Executing task: c:\Program Files\Blender Foundation\Blender 2.90\blender.exe --python c:\Users\Paul Brassington\.vscode\extensions\jacqueslucke.blender-development-0.0.15\pythonFiles\launch.py <

Read prefs: C:\Users\Paul Brassington\AppData\Roaming\Blender Foundation\Blender\2.90\config\userpref.blend
found bundled python: c:\Program Files\Blender Foundation\Blender 2.90\2.90\python
[{'load_dir': 'c:\\Users\\Paul Brassington\\Documents\\Code\\Blender\\PBB', 'module_name': 'PBB'}]
Read prefs: C:\Users\Paul Brassington\AppData\Roaming\Blender Foundation\Blender\2.90\config\userpref.blend
found bundled python: c:\Program Files\Blender Foundation\Blender 2.90\2.90\python
unknown argument, loading as file: -m
Error: Cannot read file 'c:\Program Files\Blender Foundation\Blender 2.90\-m': No such file or directory
Error: argument has no '.blend' file extension, not using as new file, exiting! c:\Program Files\Blender Foundation\Blender 2.90\-m
Saved session recovery to 'C:\Users\PAULBR~1\AppData\Local\Temp\quit.blend'

Blender quit

################################################################################
>   could not install debugpy
################################################################################

Saved session recovery to 'C:\Users\PAULBR~1\AppData\Local\Temp\quit.blend'

### PR DESCRIPTION
**Pull request by Mateusz-Grzelinski**
Blender 2.,80, 2.91, 2.93 failed to install because of wrong python path.

Most likely fixes #99 #93 #80 #31

- improved finding python path for older versions
- improved typehints to be compatible with python 3.7
- added log for pip call
- fixed debugpy issue when `sys.executable` is not pointing to python what causes timeout 

Tested in basic way with different versions:
```
blender-2.80-windows64
blender-2.83.20-windows-x64
blender-2.90.1-windows64
blender-2.93.18-windows-x64
blender-3.0
blender-3.3.21-windows-x64
blender-3.5.1
blender-3.6.14-windows-x64
blender-4.2.0-windows-x64
```

can be squashed, just remember to iclude sensible merge message.

### CODE REVIEW

**Review by JacquesLucke — APPROVED** [review]

**Comment by CGArtPython** [comment]
@Mateusz-Grzelinski Out of curiosity, why are we improving typehints for Python 3.7 if Blender 2.8 had Python 3.10 ?

**Comment by Mateusz-Grzelinski** [comment]
what are you talking about?
```python
>>> bpy.app.version
(2, 80, 75)

>>> import sys; sys.version
'3.7.0 (default, Aug 26 2018, 16:05:01) [MSC v.1900 64 bit (AMD64)]'
```

```python
>>> bpy.app.version
(2, 83, 20)

>>> import sys; sys.version
'3.7.4 (default, Feb 17 2020, 16:23:28) [MSC v.1916 64 bit (AMD64)]'
```

**Comment by CGArtPython** [comment]
Yeah, 
Just realized my Blender 2.8 is booting a newer version of Blender. 🫠
