### ISSUE TITLE
Extension not working with blender 2.79

### ISSUE THREAD

**Issue by SalmaG98** [JacquesLucke/blender_vscode#144]
Hello,

Thank you for your work :)

Is there anyone who was succesfull in running this extension with a blender < 2.8 ? I have a constraint on the headless server I use for blender (OpenGL 2.1), I cannot ask for a higher opengl install, but I still would like to use this extenstion.

I have tried a bunch of things:
1. Installing blender 2.79 version: solved the OpenGL 3.3 error requirement but f strings in https://github.com/JacquesLucke/blender_vscode/blob/master/pythonFiles/launch.py cause SyntaxError because this blender version uses python 3.5
2. Installing the[ latest 2.7 build ](https://download.blender.org/release/Blender2.79/latest/) for blender working with python 3.7m: solved the f string problem, but the install of flask package causes a version issue.
3. Manually replacing blender 2.79 latest build's python with a symlink to another python interpreter from a conda environment I created (python 3.7.0) with flask, debugpy and requests installed: solved package problems but now https://github.com/JacquesLucke/blender_vscode/blob/d83fcdd67f36d8bbe3303d65001a8aa595c998a7/pythonFiles/include/blender_vscode/utils.py#L27 causes the exception ```AttributeError: 'bpy.app' object has no attribute 'timers'```

It seems it is not possible to use a blender version older than 2.8, is there maybe an older version of this extension I can use in order to use blender 2.79?

**Comment by Mateusz-Grzelinski** [comment]
Hey @SalmaG98 is it still relevant? I am treating 2.80 as oldest supported verions so I am reluctant to spend time to make 2.79 work... Even the 2.80 support was broken recently #174
